// Fix duplicate graphviz map IDs generated by sphinx-needs needflow.
// Multiple needflow diagrams on a page all get <map id="needflow">,
// but HTML requires unique IDs — browsers only match the first one.
document.addEventListener('DOMContentLoaded', function() {
    var maps = document.querySelectorAll('map[name="needflow"]');
    maps.forEach(function(map, i) {
        var uniqueName = 'needflow-' + i;
        map.id = uniqueName;
        map.name = uniqueName;
        var figure = map.closest('figure');
        if (figure) {
            var img = figure.querySelector('img[usemap="#needflow"]');
            if (img) img.setAttribute('usemap', '#' + uniqueName);
        }
    });
});
